package main

const indexHTML = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QnapAssistant</title><style>
body{font-family:system-ui;margin:0;background:#101217;color:#eee}.wrap{max-width:1180px;margin:auto;padding:20px}.card{background:#191d25;border:1px solid #303745;border-radius:14px;padding:16px;margin:12px 0}input,select,button,textarea{background:#0f1218;color:#eee;border:1px solid #3b4454;border-radius:8px;padding:9px}input,select,textarea{width:100%;box-sizing:border-box}textarea{min-height:70px}button{cursor:pointer;margin:3px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.ok{color:#65d98b}.off{color:#e6bd5a}.bad{color:#f27a7a}pre{white-space:pre-wrap;max-height:380px;overflow:auto;background:#0c0e12;padding:12px;border-radius:8px}label{font-size:12px;color:#aeb7c6}.hint{font-size:12px;color:#8f9bad;margin:8px 0}.profile{border:1px solid #303745;border-radius:10px;padding:12px}.secret{font-family:monospace}.row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row button{flex:0 0 auto}h3{margin:2px 0 12px}</style></head><body><div class="wrap">
<h1>QnapAssistant</h1>
<div class="card"><h3>Runtime</h3><div><b>LLM:</b> <span id="status">...</span> <button onclick="act('start')">Load / Check</button><button onclick="act('stop')">Unload local</button><button onclick="act('restart')">Restart / Check</button></div><div><b>Voice:</b> <span id="voiceStatus">...</span> <button onclick="voiceAct('start')">Start worker</button><button onclick="voiceAct('stop')">Stop worker</button><button onclick="voiceAct('restart')">Restart worker</button></div></div>

<div class="card"><h3>Model residency / auto-unload</h3><div class="grid">
<div class="profile"><b>LLM (local Qwen)</b><label>Auto unload</label><select id="LLM_AUTO_UNLOAD"><option value="0">Disabled / resident</option><option value="1">Enabled</option></select><label>Idle seconds</label><input id="LLM_IDLE_TIMEOUT_SECONDS" type="number" min="1"></div>
<div class="profile"><b>ASR (SenseVoice)</b><label>Auto unload</label><select id="ASR_AUTO_UNLOAD"><option value="0">Disabled / resident</option><option value="1">Enabled</option></select><label>Idle seconds</label><input id="ASR_IDLE_TIMEOUT_SECONDS" type="number" min="1"></div>
<div class="profile"><b>TTS (Piper / Supertonic)</b><label>Auto unload</label><select id="TTS_AUTO_UNLOAD"><option value="0">Disabled / resident</option><option value="1">Enabled</option></select><label>Idle seconds</label><input id="TTS_IDLE_TIMEOUT_SECONDS" type="number" min="1"></div>
</div><div class="hint">ASR/TTS auto-unload releases only that model/session. The voice worker remains available and reloads the required model lazily.</div><button onclick="saveResidency()">Save residency</button></div>

<div class="card"><h3>LLM provider</h3><div class="grid"><div><label>Provider</label><select id="LLM_PROVIDER"><option value="local">Local Qwen / llama.cpp</option><option value="openrouter">OpenRouter</option></select></div></div><button onclick="saveProvider()">Apply provider</button><div class="hint">Switching provider unloads the local llama process. Voice sessions/history are provider-independent.</div></div>

<div class="card"><h3>OpenRouter</h3>
<div class="grid"><div><label>API key</label><input id="orKey" class="secret" type="password" autocomplete="new-password" placeholder="sk-or-... (never displayed after save)"></div><div><label>Key status</label><div id="orKeyStatus" class="hint">...</div></div></div><button onclick="saveORKey()">Save API key</button><button onclick="clearORKey()">Clear API key</button>
<div class="grid"><div><label>Base URL</label><input id="OPENROUTER_BASE_URL"></div><div><label>Primary model</label><input id="OPENROUTER_MODEL" placeholder="openrouter/free"></div><div><label>Fallback models (comma separated, ordered)</label><input id="OPENROUTER_FALLBACK_MODELS"></div><div><label>Preset</label><input id="OPENROUTER_PRESET"></div></div>
<div class="grid"><div><label>Model browser</label><select id="orModels"></select></div><div><label>List</label><select id="orFree"><option value="1">Free models only</option><option value="0">All models</option></select></div></div><button onclick="loadORModels()">Load model list</button><button onclick="useORModel()">Use selected as primary</button>
<div class="grid"><div><label>Temperature (blank=voice/default)</label><input id="OPENROUTER_TEMPERATURE"></div><div><label>Top P (blank=default)</label><input id="OPENROUTER_TOP_P"></div><div><label>Reasoning effort</label><select id="OPENROUTER_REASONING_EFFORT"><option value="">Model default</option><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></div><div><label>Provider sort</label><select id="OPENROUTER_PROVIDER_SORT"><option value="">OpenRouter default</option><option value="price">price</option><option value="throughput">throughput</option><option value="latency">latency</option></select></div></div>
<div class="grid"><div><label>Allow provider fallbacks</label><select id="OPENROUTER_ALLOW_FALLBACKS"><option value="1">Yes</option><option value="0">No</option></select></div><div><label>Require parameter support</label><select id="OPENROUTER_REQUIRE_PARAMETERS"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Data collection</label><select id="OPENROUTER_DATA_COLLECTION"><option value="">Default</option><option value="deny">deny</option><option value="allow">allow</option></select></div><div><label>Zero data retention only</label><select id="OPENROUTER_ZDR"><option value="">Default</option><option value="1">Yes</option><option value="0">No</option></select></div></div>
<div class="grid"><div><label>Provider only (CSV)</label><input id="OPENROUTER_PROVIDER_ONLY"></div><div><label>Provider ignore (CSV)</label><input id="OPENROUTER_PROVIDER_IGNORE"></div><div><label>Max prompt price / 1M tokens</label><input id="OPENROUTER_MAX_PRICE_PROMPT"></div><div><label>Max completion price / 1M tokens</label><input id="OPENROUTER_MAX_PRICE_COMPLETION"></div><div><label>HTTP-Referer (optional)</label><input id="OPENROUTER_HTTP_REFERER"></div><div><label>X-Title</label><input id="OPENROUTER_X_TITLE"></div></div>
<button onclick="saveORSettings()">Save OpenRouter settings</button><button onclick="testOR()">Safe free test (8 tokens)</button><pre id="orTest"></pre><div class="hint">Safe test forces <code>openrouter/free</code> unless the API is explicitly called with allow_paid=true. The web UI never does that.</div></div>

<div class="card"><h3>Local GGUF models</h3><select id="models"></select><button onclick="selectModel()">Select local model</button><div class="grid"><div><label>Download URL</label><input id="dlurl"></div><div><label>Filename (.gguf)</label><input id="dlname"></div></div><button onclick="downloadModel()">Download to Public</button><div id="dlstate"></div></div>

<div class="card"><h3>Local llama.cpp settings</h3><div class="grid"><div><label>Qwen3 Thinking</label><select id="thinking"><option value="off">OFF - fast</option><option value="on">ON - think</option><option value="passthrough">Client / model default</option></select></div></div><button onclick="setThinking()">Apply Thinking Mode</button><div id="form" class="grid"></div><label>EXTRA_ARGS</label><input id="EXTRA_ARGS"><button onclick="saveLocalCfg()">Save local LLM settings</button></div>

<div class="card"><h3>Voice client profiles</h3><div class="grid"><div><label>Default profile</label><select id="VOICE_PROFILE_DEFAULT"><option value="generic">Generic</option><option value="m5go">M5GO</option></select></div></div><div class="grid"><div class="profile"><b>Generic</b><div class="grid"><div><label>Sample rate (0=native)</label><input id="VOICE_GENERIC_SAMPLE_RATE"></div><div><label>Peak target (0=off)</label><input id="VOICE_GENERIC_PEAK_TARGET"></div><div><label>Strip emoji</label><select id="VOICE_GENERIC_STRIP_EMOJI"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Stream format</label><select id="VOICE_GENERIC_STREAM_FORMAT"><option value="ndjson">NDJSON + base64</option><option value="multipart">Multipart binary</option></select></div><div><label>Chunk min chars</label><input id="VOICE_GENERIC_CHUNK_MIN_CHARS"></div><div><label>Chunk max chars</label><input id="VOICE_GENERIC_CHUNK_MAX_CHARS"></div></div></div><div class="profile"><b>M5GO</b><div class="grid"><div><label>Sample rate</label><input id="VOICE_M5_SAMPLE_RATE"></div><div><label>Peak target</label><input id="VOICE_M5_PEAK_TARGET"></div><div><label>Strip emoji</label><select id="VOICE_M5_STRIP_EMOJI"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Stream format</label><select id="VOICE_M5_STREAM_FORMAT"><option value="multipart">Multipart binary</option><option value="ndjson">NDJSON + base64</option></select></div><div><label>Chunk min chars</label><input id="VOICE_M5_CHUNK_MIN_CHARS"></div><div><label>Chunk max chars</label><input id="VOICE_M5_CHUNK_MAX_CHARS"></div></div></div></div><button onclick="saveVoiceProfiles()">Save voice profiles</button></div>

<div class="card"><h3>Voice response</h3><div class="grid"><div><label>Reply max tokens (0=backend default)</label><input id="VOICE_REPLY_MAX_TOKENS"></div><div><label>Temperature</label><input id="VOICE_REPLY_TEMPERATURE"></div></div><label>System prompt</label><textarea id="VOICE_SYSTEM_PROMPT"></textarea><button onclick="saveVoiceResponse()">Save voice response</button></div>
<div class="card"><h3>Logs</h3><button onclick="logs('llama')">llama-server</button><button onclick="logs('admin')">manager</button><pre id="logs"></pre></div>
</div><script>
const localKeys=['THREADS','THREADS_BATCH','CONTEXT','BATCH','UBATCH','PARALLEL','ADMIN_PORT','BACKEND_PORT'];
const residencyKeys=['LLM_AUTO_UNLOAD','LLM_IDLE_TIMEOUT_SECONDS','ASR_AUTO_UNLOAD','ASR_IDLE_TIMEOUT_SECONDS','TTS_AUTO_UNLOAD','TTS_IDLE_TIMEOUT_SECONDS'];
const orKeys=['OPENROUTER_BASE_URL','OPENROUTER_MODEL','OPENROUTER_FALLBACK_MODELS','OPENROUTER_PRESET','OPENROUTER_TEMPERATURE','OPENROUTER_TOP_P','OPENROUTER_REASONING_EFFORT','OPENROUTER_PROVIDER_SORT','OPENROUTER_ALLOW_FALLBACKS','OPENROUTER_REQUIRE_PARAMETERS','OPENROUTER_DATA_COLLECTION','OPENROUTER_ZDR','OPENROUTER_PROVIDER_ONLY','OPENROUTER_PROVIDER_IGNORE','OPENROUTER_MAX_PRICE_PROMPT','OPENROUTER_MAX_PRICE_COMPLETION','OPENROUTER_HTTP_REFERER','OPENROUTER_X_TITLE'];
const voiceKeys=['VOICE_PROFILE_DEFAULT','VOICE_GENERIC_SAMPLE_RATE','VOICE_GENERIC_PEAK_TARGET','VOICE_GENERIC_STRIP_EMOJI','VOICE_GENERIC_STREAM_FORMAT','VOICE_GENERIC_CHUNK_MIN_CHARS','VOICE_GENERIC_CHUNK_MAX_CHARS','VOICE_M5_SAMPLE_RATE','VOICE_M5_PEAK_TARGET','VOICE_M5_STRIP_EMOJI','VOICE_M5_STREAM_FORMAT','VOICE_M5_CHUNK_MIN_CHARS','VOICE_M5_CHUNK_MAX_CHARS'];
async function j(u,o){let r=await fetch(u,o);if(!r.ok)throw new Error(await r.text());return r.json()}
function values(keys){let c={};for(let k of keys){let e=document.getElementById(k);if(e)c[k]=e.value}return c}
async function putCfg(c){await j('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});await refresh()}
async function refresh(){try{let s=await j('/api/status');let remote=s.llm_provider==='openrouter';status.textContent=(remote?('OpenRouter / '+(s.openrouter_model||'-')+' / key '+(s.openrouter_key_configured?'set':'missing')):('Local / '+(s.llm_loaded?'loaded':'unloaded')))+' | RAM free '+Math.round((s.memory_available_bytes||0)/1048576)+' MB | load '+(s.load1||'-');status.className=s.llm_ready?'ok':'off';dlstate.textContent=s.download.active?('Downloading '+s.download.name+': '+Math.round((s.download.written_bytes||0)/1048576)+' MB'):(s.download.error||'');let v=await j('/api/voice/status');if(v.worker_running){voiceStatus.textContent='worker up | ASR '+(v.asr_loaded?'hot':'cold')+(v.asr_auto_unload?' / auto':'')+' | Piper '+(v.piper_resident?'hot':'cold')+(v.tts_auto_unload?' / auto':'')+' | Supertonic '+(v.tts_loaded?'hot':'lazy');voiceStatus.className='ok'}else{voiceStatus.textContent='worker stopped / models cold';voiceStatus.className='off'}let c=await j('/api/config');LLM_PROVIDER.value=c.LLM_PROVIDER||'local';for(let k of localKeys.concat(residencyKeys,orKeys,voiceKeys,['VOICE_REPLY_MAX_TOKENS','VOICE_REPLY_TEMPERATURE','VOICE_SYSTEM_PROMPT'])){let e=document.getElementById(k);if(e)e.value=c[k]??''}EXTRA_ARGS.value=c.EXTRA_ARGS||'';let th=await j('/api/thinking');thinking.value=th.mode||'off';let key=await j('/api/openrouter/key');orKeyStatus.textContent=key.configured?('configured / fingerprint '+key.fingerprint):'not configured';let ms=await j('/api/models');models.innerHTML=ms.map(m=>'<option value="'+m.path+'" '+(m.selected?'selected':'')+'>'+m.name+' ('+(m.size/1048576).toFixed(0)+' MB)</option>').join('')}catch(e){status.textContent=e.message;status.className='bad'}}
async function act(x){await j('/api/llm/'+x,{method:'POST'});refresh()}
async function voiceAct(x){await j('/api/voice/'+x,{method:'POST'});refresh()}
async function saveResidency(){await putCfg(values(residencyKeys))}
async function saveProvider(){await putCfg({LLM_PROVIDER:LLM_PROVIDER.value})}
async function saveORKey(){if(!orKey.value){alert('API key is empty');return}await j('/api/openrouter/key',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:orKey.value})});orKey.value='';refresh()}
async function clearORKey(){await j('/api/openrouter/key',{method:'DELETE'});orKey.value='';refresh()}
async function loadORModels(){orModels.innerHTML='<option>loading...</option>';try{let d=await j('/api/openrouter/models?free='+orFree.value);orModels.innerHTML=d.models.map(m=>'<option value="'+m.id+'">'+(m.free?'[FREE] ':'')+m.name+' — '+m.id+' / ctx '+(m.context_length||'?')+'</option>').join('')}catch(e){orModels.innerHTML='<option>'+e.message+'</option>'}}
function useORModel(){if(orModels.value)OPENROUTER_MODEL.value=orModels.value}
async function saveORSettings(){await putCfg(values(orKeys))}
async function testOR(){orTest.textContent='testing free route...';try{let d=await j('/api/openrouter/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({max_tokens:8})});orTest.textContent=JSON.stringify(d,null,2)}catch(e){orTest.textContent=e.message}}
async function setThinking(){await j('/api/thinking',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:thinking.value})});refresh()}
async function saveLocalCfg(){let c=values(localKeys);c.EXTRA_ARGS=EXTRA_ARGS.value;await putCfg(c)}
async function saveVoiceProfiles(){await putCfg(values(voiceKeys))}
async function saveVoiceResponse(){await putCfg(values(['VOICE_REPLY_MAX_TOKENS','VOICE_REPLY_TEMPERATURE','VOICE_SYSTEM_PROMPT']))}
async function selectModel(){await j('/api/models/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:models.value})});refresh()}
async function downloadModel(){await j('/api/models/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({URL:dlurl.value,Filename:dlname.value})});refresh()}
async function logs(t){let r=await fetch('/api/logs?target='+t+'&lines=400');logs.textContent=await r.text()}
form.innerHTML=localKeys.map(k=>'<div><label>'+k+'</label><input id="'+k+'"></div>').join('');refresh();setInterval(refresh,5000);
</script></body></html>`
