package main

import "strings"

const openRouterModelTableAnchor = `<div id="orPolicyStatus" class="or-model-meta"></div>`

const openRouterModelTableHTML = `<style>
.or-model-manager{margin-top:10px}.or-model-table-wrap{overflow-x:auto;border:1px solid #303745;border-radius:10px;margin-top:8px}.or-model-table{width:100%;border-collapse:collapse;min-width:980px;font-size:12px}.or-model-table th,.or-model-table td{padding:8px;border-bottom:1px solid #303745;text-align:left;vertical-align:top}.or-model-table th{position:sticky;top:0;background:#171b23;color:#c9d2e2;white-space:nowrap}.or-model-table tr:last-child td{border-bottom:0}.or-model-table tr.or-selected{outline:1px solid #65d98b;outline-offset:-1px;background:#17211d}.or-model-table tr.or-blocked{opacity:.62}.or-model-table code{font-size:11px}.or-table-pager{display:flex;gap:8px;align-items:center;justify-content:flex-end;flex-wrap:wrap;margin-top:8px}.or-table-pager span{font-size:12px;color:#aeb7c6}.or-badge{display:inline-block;border:1px solid #3b4454;border-radius:999px;padding:1px 6px;margin:0 3px 3px 0;white-space:nowrap}.or-price{white-space:nowrap}.or-model-name{font-weight:600;color:#e7ecf5}.or-model-id{color:#8f9bad;word-break:break-all}.or-sort-grid{grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}.or-selected-summary{margin-top:8px;padding:8px;border-radius:8px;background:#10141b}
</style>
<div id="orModelManager" class="or-model-manager">
  <div class="grid or-sort-grid">
    <div><label>モデル検索</label><input id="orModelSearch" placeholder="名前 / model id"></div>
    <div><label>状態フィルタ</label><select id="orModelStatusFilter"><option value="all">すべて</option><option value="allowed">Policy利用可</option><option value="restricted">Policy制限</option><option value="blacklist">Blacklist</option><option value="cooldown">Cooldown</option><option value="used">利用実績あり</option><option value="unused">未使用</option></select></div>
    <div><label>料金フィルタ</label><select id="orModelCostFilter"><option value="all">無料 + 有料</option><option value="free">無料のみ</option><option value="paid">有料のみ</option></select></div>
    <div><label>並び順</label><select id="orModelSort"><option value="usage">利用回数</option><option value="last_used">最終利用</option><option value="newest">追加日</option><option value="price_total">入出力合計単価</option><option value="price_prompt">入力単価</option><option value="price_completion">出力単価</option><option value="success_rate">成功率</option><option value="context">Context</option><option value="name">名前</option></select></div>
    <div><label>順序</label><select id="orModelDir"><option value="desc">降順</option><option value="asc">昇順</option></select></div>
    <div><label>1ページ</label><select id="orModelPageSize"><option value="10">10件</option><option value="20">20件</option></select></div>
  </div>
  <div class="or-actions"><button onclick="loadORModels()">一覧を再取得</button><button onclick="resetORPolicyState()">Policy再評価</button><button onclick="resetORUsageHistory()">利用実績をリセット</button></div>
  <div id="orModelTableInfo" class="or-model-meta"></div>
  <div class="or-model-table-wrap"><table class="or-model-table"><thead><tr><th>選択</th><th>モデル</th><th>Policy / 状態</th><th>利用実績</th><th>追加日</th><th>料金 / 1M tokens</th><th>Context</th></tr></thead><tbody id="orModelTableBody"></tbody></table></div>
  <div class="or-table-pager"><button id="orModelPrev" onclick="orModelPageMove(-1)">← 前</button><span id="orModelPageLabel"></span><button id="orModelNext" onclick="orModelPageMove(1)">次 →</button></div>
  <div id="orSelectedModelMeta" class="or-model-meta or-selected-summary"></div>
</div>`

const openRouterModelTableScript = `<script>
window.orModelPage=1;window.orSelectedModel='';
function orTableNumber(v){let n=Number(v);return Number.isFinite(n)?n:null;}
function orTableDateUnix(v){let n=orTableNumber(v);if(!n||n<=0)return '-';return new Date(n*1000).toLocaleDateString('ja-JP');}
function orTableDateISO(v){let t=Date.parse(v||'');return Number.isFinite(t)?t:null;}
function orTableLastUsed(m){let a=orTableDateISO(m.voice_last_success_at),b=orTableDateISO(m.voice_last_failure_at);if(a===null)return b;if(b===null)return a;return Math.max(a,b);}
function orTableUseCount(m){return Number(m.voice_use_count??((m.voice_success_count||0)+(m.voice_failure_count||0)))||0;}
function orTableSuccessRate(m){let total=orTableUseCount(m);return total?((Number(m.voice_success_count)||0)/total):null;}
function orTablePrice(m,key){let p=m.pricing||{};let n=Number(p[key]);return Number.isFinite(n)?n:null;}
function orTableTotalPrice(m){let a=orTablePrice(m,'prompt'),b=orTablePrice(m,'completion');if(a===null&&b===null)return null;return (a||0)+(b||0);}
function orTableCooldown(m){if(!m||!m.voice_cooldown_until)return false;let t=Date.parse(m.voice_cooldown_until);return Number.isFinite(t)&&t>Date.now();}
function orTableStatusText(m){let x=[];if(m.policy_checked)x.push(m.policy_allowed?'Policy OK':'Policy制限');else x.push('Policy未確認');if(m.voice_blacklisted)x.push('BLACKLIST');else if(orTableCooldown(m))x.push('COOLDOWN');if(m.moderated)x.push('MOD');return x.join(' / ');}
function orTableLoadPrefs(){let d={status:'all',cost:'all',sort:'usage',dir:'desc',size:'10',search:''};try{let v=JSON.parse(localStorage.getItem('qnap.orModelTable')||'{}');Object.assign(d,v||{})}catch(e){}return d;}
function orTableSavePrefs(){try{localStorage.setItem('qnap.orModelTable',JSON.stringify({status:el('orModelStatusFilter').value,cost:el('orModelCostFilter').value,sort:el('orModelSort').value,dir:el('orModelDir').value,size:el('orModelPageSize').value,search:el('orModelSearch').value}))}catch(e){}}
function orTableApplyPrefs(){let p=orTableLoadPrefs();for(let [id,v] of [['orModelStatusFilter',p.status],['orModelCostFilter',p.cost],['orModelSort',p.sort],['orModelDir',p.dir],['orModelPageSize',p.size],['orModelSearch',p.search]]){let e=el(id);if(e)e.value=v||e.value;}}
function orTableMatches(m){let q=(el('orModelSearch').value||'').trim().toLowerCase();if(q&&!((m.name||'').toLowerCase().includes(q)||(m.id||'').toLowerCase().includes(q)))return false;let cost=el('orModelCostFilter').value;if(cost==='free'&&!m.free)return false;if(cost==='paid'&&m.free)return false;let st=el('orModelStatusFilter').value;let used=orTableUseCount(m)>0;if(st==='allowed'&&!(m.policy_checked&&m.policy_allowed))return false;if(st==='restricted'&&!(m.policy_checked&&!m.policy_allowed))return false;if(st==='blacklist'&&!m.voice_blacklisted)return false;if(st==='cooldown'&&!orTableCooldown(m))return false;if(st==='used'&&!used)return false;if(st==='unused'&&used)return false;return true;}
function orTableSortValue(m,key){switch(key){case'usage':return orTableUseCount(m);case'last_used':return orTableLastUsed(m);case'newest':return Number(m.created)||null;case'price_total':return orTableTotalPrice(m);case'price_prompt':return orTablePrice(m,'prompt');case'price_completion':return orTablePrice(m,'completion');case'success_rate':return orTableSuccessRate(m);case'context':return Number(m.context_length)||null;case'name':return (m.name||m.id||'').toLowerCase();default:return 0;}}
function orTableCompare(a,b,key,dir){let x=orTableSortValue(a,key),y=orTableSortValue(b,key);let nx=(x===null||x===undefined||x===''),ny=(y===null||y===undefined||y==='');if(nx&&ny)return (a.name||a.id||'').localeCompare(b.name||b.id||'');if(nx)return 1;if(ny)return -1;let c=typeof x==='string'?x.localeCompare(y):(x<y?-1:(x>y?1:0));if(c===0)c=(a.name||a.id||'').localeCompare(b.name||b.id||'');return dir==='asc'?c:-c;}
function orTableFiltered(){let rows=(window.orCatalog||[]).filter(orTableMatches);let key=el('orModelSort').value,dir=el('orModelDir').value;rows.sort((a,b)=>orTableCompare(a,b,key,dir));return rows;}
function orTableSetSelected(id){window.orSelectedModel=id||'';let s=el('orModels');if(s&&id){if(!Array.from(s.options).some(o=>o.value===id)){let o=document.createElement('option');o.value=id;o.textContent=id;s.appendChild(o)}s.value=id}renderORModelTable();updateORModelMeta();}
function renderORModelTable(){let body=el('orModelTableBody');if(!body)return;let rows=orTableFiltered();let size=Number(el('orModelPageSize').value)||10;let pages=Math.max(1,Math.ceil(rows.length/size));window.orModelPage=Math.min(Math.max(1,window.orModelPage||1),pages);let start=(window.orModelPage-1)*size;let page=rows.slice(start,start+size);body.innerHTML=page.map(m=>{let selected=(m.id===window.orSelectedModel);let blocked=!!(m.policy_checked&&!m.policy_allowed);let rowClass=(selected?'or-selected ':'')+(blocked?'or-blocked':'');let badges=[];if(m.free)badges.push('<span class="or-badge or-good">FREE</span>');if(m.policy_checked)badges.push('<span class="or-badge '+(m.policy_allowed?'or-good':'bad')+'">'+(m.policy_allowed?'Policy OK':'Policy制限')+'</span>');else badges.push('<span class="or-badge">未確認</span>');if(m.voice_blacklisted)badges.push('<span class="or-badge bad">BLACKLIST</span>');else if(orTableCooldown(m))badges.push('<span class="or-badge off">COOLDOWN</span>');if(m.moderated)badges.push('<span class="or-badge">MOD</span>');let total=orTableUseCount(m),rate=orTableSuccessRate(m);let usage='合計 '+total+' · S'+(m.voice_success_count||0)+'/F'+(m.voice_failure_count||0)+(rate===null?'':' · '+(rate*100).toFixed(0)+'%');let p=m.pricing||{};let price=m.free?'FREE':('in '+orMillionPrice(p.prompt)+' / out '+orMillionPrice(p.completion));let disabled=blocked?'disabled':'';return '<tr class="'+rowClass+'"><td><input type="radio" name="orModelPick" '+(selected?'checked':'')+' '+disabled+' onclick="orTableSetSelected('+JSON.stringify(m.id).replace(/"/g,'&quot;')+')"></td><td><div class="or-model-name">'+orEsc(m.name||m.id)+'</div><div class="or-model-id">'+orEsc(m.id)+'</div></td><td>'+badges.join('')+'</td><td>'+orEsc(usage)+'</td><td>'+orEsc(orTableDateUnix(m.created))+'</td><td class="or-price">'+orEsc(price)+'</td><td>'+orEsc(Number(m.context_length||0).toLocaleString()||'-')+'</td></tr>'}).join('');el('orModelPageLabel').textContent=(rows.length?((start+1)+'–'+Math.min(start+size,rows.length)+' / '+rows.length):'0件')+' · '+window.orModelPage+'/'+pages+'ページ';el('orModelPrev').disabled=window.orModelPage<=1;el('orModelNext').disabled=window.orModelPage>=pages;let info=el('orModelTableInfo');if(info)info.textContent='全 '+(window.orCatalog||[]).length+'件 / 条件一致 '+rows.length+'件 · 表示設定はこのブラウザに保存';}
window.orModelPageMove=function(delta){window.orModelPage=(window.orModelPage||1)+delta;renderORModelTable();};
window.orModelTableChanged=function(){window.orModelPage=1;orTableSavePrefs();renderORModelTable();};
window.updateORModelMeta=function(){let id=window.orSelectedModel||(el('orModels')?el('orModels').value:'');let m=(window.orCatalog||[]).find(x=>x.id===id);let box=el('orSelectedModelMeta');if(!box)return;if(!m){box.textContent=id?('選択: '+id):'モデルを選択してください';return}let bits=['選択: '+m.id,orTableStatusText(m),'利用 '+orTableUseCount(m)+'回'];if(m.created)bits.push('追加 '+orTableDateUnix(m.created));if(m.context_length)bits.push('ctx '+Number(m.context_length).toLocaleString());let pricing=(typeof renderORPricing==='function')?renderORPricing(m):'';if(pricing)bits.push(pricing);if(m.voice_blacklist_reason)bits.push('理由 '+m.voice_blacklist_reason);box.textContent=bits.filter(Boolean).join(' · ');box.className='or-model-meta or-selected-summary '+((m.policy_checked&&!m.policy_allowed)||m.voice_blacklisted?'bad':'');};
window.loadORModels=async function(){let current=(el('OPENROUTER_MODEL').value||window.orSelectedModel||'openrouter/free').trim();let info=el('orModelTableInfo');if(info)info.textContent='OpenRouterモデル一覧を取得中...';try{let d=await j('/api/openrouter/models?free=0');window.orCatalog=d.models||[];if(!window.orSelectedModel)window.orSelectedModel=current;let s=el('orModels');if(s){s.innerHTML=window.orCatalog.map(m=>'<option value="'+orEsc(m.id)+'">'+orEsc(m.id)+'</option>').join('');if(current&&!window.orCatalog.some(m=>m.id===current)){let o=document.createElement('option');o.value=current;o.textContent=current;s.appendChild(o)}s.value=window.orSelectedModel||current}let ps=el('orPolicyStatus');if(ps){let restricted=window.orCatalog.filter(m=>m.policy_checked&&!m.policy_allowed).length,blacklisted=window.orCatalog.filter(m=>m.voice_blacklisted).length,allowed=window.orCatalog.filter(m=>m.policy_checked&&m.policy_allowed).length;if(d.policy_checked){ps.textContent='Policy判定: 利用可 '+allowed+' / 制限 '+restricted+' · Blacklist '+blacklisted+' · 429/入力内容依存Guardrailは実行時判定';ps.className='or-model-meta '+(restricted||blacklisted?'off':'or-good')}else if(d.policy_error){ps.textContent='Policy判定取得失敗: '+d.policy_error;ps.className='or-model-meta off'}else{ps.textContent='APIキー保存後にPrivacy/Guardrail適合性を判定します。';ps.className='or-model-meta'}}renderORModelTable();updateORModelMeta();}catch(e){if(info)info.textContent='モデル一覧の取得に失敗: '+e.message;}};
window.applyORSelected=async function(){let model=window.orSelectedModel||(el('orModels')?el('orModels').value:'');if(!model){alert('表からモデルを選択してください');return}let m=(window.orCatalog||[]).find(x=>x.id===model);if(m&&m.policy_checked&&!m.policy_allowed){alert('現在のOpenRouter Policyでは利用できません。Policy変更後に「Policy再評価」を実行してください。');return}el('OPENROUTER_MODEL').value=model;await putCfg({LLM_PROVIDER:'openrouter',OPENROUTER_MODEL:model});el('orTest').textContent='OpenRouterを使用: '+model;};
window.resetORPolicyState=async function(){if(!confirm('OpenRouterのPolicy/Privacy/Guardrail設定を変更しましたか？ Policy由来Blacklistを解除し、最新Policyで再評価します。利用回数は保持します。'))return;let info=el('orModelTableInfo');if(info)info.textContent='Policy状態をクリアして再評価中...';await j('/api/openrouter/voice-health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset_policy_state'})});await loadORModels();if(typeof refreshORVoiceHealth==='function')refreshORVoiceHealth().catch(()=>{});};
window.resetORUsageHistory=async function(){if(!confirm('成功/失敗回数、Blacklist、Cooldownを含むOpenRouter音声利用実績をすべて消去しますか？'))return;await j('/api/openrouter/voice-health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset_history'})});await loadORModels();if(typeof refreshORVoiceHealth==='function')refreshORVoiceHealth().catch(()=>{});};
function initORModelTable(){let old=el('orModels');if(old){let g=old.closest('.grid');if(g)g.style.display='none'}let hb=el('orVoiceHealth');if(hb){hb.style.display='none';let p=hb.previousElementSibling;if(p&&p.classList.contains('or-actions'))p.style.display='none'}for(let id of ['orModelSearch','orModelStatusFilter','orModelCostFilter','orModelSort','orModelDir','orModelPageSize']){let e=el(id);if(e)e.addEventListener(id==='orModelSearch'?'input':'change',orModelTableChanged)}orTableApplyPrefs();let main=document.querySelector('.or-main');if(main){for(let b of main.querySelectorAll('button')){if((b.getAttribute('onclick')||'').trim()==='loadORModels()'&&b.closest('#orModelManager')===null)b.style.display='none'}}loadORModels();}
setTimeout(initORModelTable,150);
</script>`

func injectOpenRouterModelTableUI(html string) string {
	if !strings.Contains(html, `id="orModelManager"`) {
		html = strings.Replace(html, openRouterModelTableAnchor, openRouterModelTableAnchor+openRouterModelTableHTML, 1)
	}
	if !strings.Contains(html, "function initORModelTable") {
		html = strings.Replace(html, "</body>", openRouterModelTableScript+"</body>", 1)
	}
	return html
}
